roll:
  p: 1.0
  i: 0.0
  d: 0.0
  i_limit: 25.0

pitch:
  p: 3.0
  i: 0.0
  d: 0.0
  i_limit: 25.0

yaw:
  p: 0.3
  i: 0.0
  d: 0.0
  i_limit: 25.0

altitude:
  p: 1.0
  i: 0.01
  d: 0.0
  i_limit: 0.2

# Mix matrix that maps control outputs to actuators
mix_matrix:
# roll, pitch, yaw, altitude
  - [ 1.0, -0.4,  0.0, -1.0]  # Port 
  - [-1.0, -0.4,  0.0, -1.0]  # Starboard
  - [ 0.0,  1.0,  0.0, -1.0]  # Aft
  - [ 0.0,  0.0,  1.0,  0.0]  # Rudder
